/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9cd60cdb-c240-4c86-99b7-bb7fb842a13b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NKxvz0KfY",
    "aws_user_pools_web_client_id": "4h9ib23lafled15g29k6iibi2u",
    "oauth": {}
};


export default awsmobile;
